# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/rakyll/magicmime
%global goipath         github.com/rakyll/magicmime
Version:                0.1.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Go bindings for libmagic to detect MIME types.}

%global godocs          README.md

Name:           golang-github-rakyll-magicmime
Release:        %autorelease
Summary:        Go bindings for libmagic to detect MIME types

License:        # FIXME
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: file-devel

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
#%%check
#%%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
