# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/doronbehar/pistol
%global goipath         github.com/doronbehar/pistol
Version:                0.5.2
%global tag             v0.5.2

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
General purpose file previewer designed for Ranger, Lf to make scope.sh
redundant.}

%global golicenses      LICENSE
%global godocs          README.adoc

Name:           pistol
Release:        %autorelease
Summary:        General purpose file previewer designed for Ranger, Lf to make scope.sh redundant

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

# manpage is written in asciidoc
BuildRequires: rubygem-asciidoctor
BuildRequires: file-devel

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
export LDFLAGS="-X 'main.Version=%{tag}'"
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
asciidoctor -b manpage -d manpage README.adoc
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0755 -vd                     %{buildroot}%{_mandir}/man1
install -m 0644 -vp %{name}.1*          %{buildroot}%{_mandir}/man1/
%endif

%if %{without bootstrap}
%if %{with check}
#%%check
#%%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.adoc
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/*
%{_mandir}/man1/%{name}.1*
%endif

%gopkgfiles

%changelog
%autochangelog
